### ISSUE TITLE
Notice this error using debug mode Warning: file_get_contents()

### ISSUE THREAD

**Issue by jerome281** [vendidero/woocommerce-trusted-shops#1]
When I'm in debug mode I'm seeing this error??

`Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/sites/domain.com/public_html/wp-content/plugins/woocommerce-trusted-shops/includes/class-wc-ts.php on line 265 Warning: file_get_contents(https://www.trustedshops.com/bewertung/widget/widgets/X4722C2083457B7AA52AFE6CC1CFA8EB5.gif): failed to open stream: no suitable wrapper could be found in /home/sites/domain.com/public_html/wp-content/plugins/woocommerce-trusted-shops/includes/class-wc-ts.php on line 265`

**Comment by dennisnissle** [comment]
Hi,

seems like you have allow_url_fopen disabled. We've just committed a wrapper to enable curl as replacement if allow_url_fopen is disabled.
